#!/usr/bin/env bash

config-wezterm() {
	dir="$(dirname "$(dirname "$(realpath "$0")")")/config/wezterm"
	target=~/.wezterm.lua

	echo "$target -> $dir/wezterm.lua"
	ln -sfn "$dir/wezterm.lua" "$target"

}

config-wezterm
