#!/usr/bin/env bash

install-mods() {

	# windows (git bash)
	if [[ $OSTYPE =~ ^msys ]]; then
		echo "Installation instruction for git bash windows"
		return
	fi
	# Debian/Ubuntu mods are installed to `/usr/bin/mods`
	if type apt-get &>/dev/null; then
		sudo mkdir -p /etc/apt/keyrings
		curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
		echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
		sudo apt update && sudo apt install mods
		return
	fi

	echo "OS unsupported by this installer: $OSTYPE"

}

install-mods
